# Generated by Django 5.2.17 on 2026-08-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionorder_created_by_and_more'),
        ('sales', '0003_sale_order_type_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrequest',
            name='linked_sale_item',
            field=models.ForeignKey(blank=True, help_text="If this request exists to fulfil a customer order, which order line it's for. Product and quantity are then taken from that order, not entered here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_requests', to='sales.saleitem'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='In individual units — production is automatically rounded up to whole batches.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionrequest',
            name='requested_by',
            field=models.CharField(blank=True, help_text='e.g. Main Store', max_length=120),
        ),
    ]
