# Generated by Django 5.2.17 on 2026-08-19 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0010_finishedgood_total_produced_alter_finishedgood_stock_and_more'),
        ('production', '0003_productionrequest_linked_sale_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrequest',
            name='business',
        ),
        migrations.RemoveField(
            model_name='productionrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionrequest',
            name='finished_good',
        ),
        migrations.RemoveField(
            model_name='productionrequest',
            name='linked_sale_item',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('order_type', models.CharField(choices=[('customer', 'Customer order'), ('physical_store', 'Physical store order')], default='physical_store', max_length=15)),
                ('customer_name', models.CharField(blank=True, help_text='Required for a customer order; leave blank for a physical store restock.', max_length=120)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Cash', help_text='Only relevant for customer orders — recorded on the Sale created when this completes.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('piece_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text="Snapshot of the product's selling price at order time — set automatically.", max_digits=12)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.finishedgood')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
        migrations.DeleteModel(
            name='ProductionRequest',
        ),
    ]
