# Generated by Django 5.2.17 on 2026-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_productionrequest_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('customer', 'Customer Order'), ('physical_store', 'Physical Store Order')], default='physical_store', max_length=15),
        ),
    ]
