# Generated by Django 5.2.17 on 2026-09-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finance_audit'),
        ('production', '0007_order_material_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Transfer', max_length=10),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionbatchreconciliation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='productionbatchreconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionqualitycheck',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='productionqualitycheck',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
