# Generated by Django 5.2.17 on 2026-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_order_customer_region_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Required for distribution and online orders; leave blank for a physical store restock.', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Cash', help_text='Relevant for distribution/online orders — recorded on the Sale created when this completes.', max_length=10),
        ),
    ]
