# Generated by Django 5.2.17 on 2026-09-02 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finance_audit'),
        ('production', '0016_productionoffcutallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoffcutallocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='productionoffcutallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
