# Generated by Django 5.2.17 on 2026-08-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('walkin', 'Walk-in (from stock)'), ('customer_order', 'Customer order (needs production)')], default='walkin', max_length=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled')], default='fulfilled', help_text='Walk-in sales are fulfilled immediately. Customer orders start pending and flip to fulfilled automatically when their linked production completes.', max_length=10),
        ),
    ]
