# Generated by Django 5.2.17 on 2026-08-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_productionrequest_business_and_more'),
        ('sales', '0003_sale_order_type_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='qty',
        ),
        migrations.AddField(
            model_name='sale',
            name='linked_order',
            field=models.ForeignKey(blank=True, help_text='Set automatically if this sale was created from a completed customer order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.order'),
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('walkin', 'Physical store'), ('customer_order', 'Customer order')], default='walkin', max_length=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='batch_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='piece_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Snapshot of the product's selling price at sale time — set automatically.", max_digits=12),
        ),
    ]
