# Generated by Django 5.2.17 on 2026-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_order_type_remove_sale_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('walkin', 'Physical Store'), ('customer_order', 'Customer Order')], default='walkin', max_length=15),
        ),
    ]
