# Generated by Django 5.2.17 on 2026-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_customer_business_alter_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='service_mode',
            field=models.CharField(blank=True, choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway / pickup'), ('delivery', 'Delivery')], default='', help_text='Restaurant service context. Blank for bakery/general sales and historical rows.', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='table_reference',
            field=models.CharField(blank=True, default='', help_text='Optional restaurant table number, tab name, or service reference.', max_length=40),
        ),
    ]
