# Generated by Django 5.2.17 on 2026-08-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_order_customer_name_alter_order_payment_method'),
        ('sales', '0006_sale_sources_distribution_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='linked_order',
            field=models.ForeignKey(blank=True, help_text='Set automatically if this sale was created from a completed distribution or online order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.order'),
        ),
    ]
