# Generated by Django 5.2.17 on 2026-09-02 15:16

import django.db.models.deletion
from django.db import migrations, models


MODULES = (
    'dashboard', 'inventory', 'procurement', 'production', 'sales',
    'expenses', 'finance', 'reports', 'users',
)


def seed_legacy_business_modules(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    BusinessModuleAccess = apps.get_model('accounts', 'BusinessModuleAccess')
    for business_id in Business.objects.values_list('id', flat=True):
        for module in MODULES:
            BusinessModuleAccess.objects.get_or_create(
                business_id=business_id,
                module=module,
                defaults={'enabled': True, 'source': 'legacy'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers_alter_customuser_groups_and_more'),
        ('core', '0003_business_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('default', 'Vertical default'), ('legacy', 'Legacy full access'), ('plan', 'Subscription plan')], default='default', max_length=12)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='core.business')),
            ],
            options={
                'ordering': ['module'],
                'constraints': [models.UniqueConstraint(fields=('business', 'module'), name='unique_business_module_access')],
            },
        ),
        migrations.RunPython(seed_legacy_business_modules, migrations.RunPython.noop),
    ]
