# Generated by Django 5.2.17 on 2026-09-07 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscription_yearly_and_gateways'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_enabled', models.BooleanField(default=True)),
                ('monnify_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payment_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription payment setting',
                'verbose_name_plural': 'subscription payment settings',
            },
        ),
    ]
