# Generated by Django 5.2.17 on 2026-08-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Business', max_length=120)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('slug', models.SlugField(default='main', max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
    ]
