from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [("core", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='CashAccount', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=80)), ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank / Transfer'), ('card', 'Card / POS'), ('other', 'Other')], default='cash', max_length=10)), ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)), ('active', models.BooleanField(default=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_cashaccount_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_cashaccount_created', to=settings.AUTH_USER_MODEL))], options={'ordering': ['name'], 'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_cash_account_per_business')]}),
        migrations.CreateModel(name='FinancialTransaction', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('transaction_type', models.CharField(choices=[('income', 'Money In'), ('outflow', 'Money Out')], max_length=10)), ('amount', models.DecimalField(decimal_places=2, max_digits=16)), ('category', models.CharField(max_length=80)), ('description', models.CharField(max_length=255)), ('payment_method', models.CharField(blank=True, default='', max_length=20)), ('reference', models.CharField(blank=True, default='', max_length=80)), ('reversed', models.BooleanField(default=False)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_financialtransaction_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_financialtransaction_created', to=settings.AUTH_USER_MODEL)), ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.cashaccount')), ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='core.financialtransaction'))], options={'ordering': ['-date', '-id']}),
        migrations.CreateModel(name='AuditLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('action', models.CharField(max_length=30)), ('model_name', models.CharField(max_length=80)), ('object_id', models.CharField(blank=True, default='', max_length=80)), ('description', models.CharField(max_length=255)), ('metadata', models.JSONField(blank=True, default=dict)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_auditlog_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_auditlog_created', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at', '-id']}),
        migrations.AlterField(model_name='auditlog', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='auditlog', name='created_by', field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='cashaccount', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='cashaccount', name='created_by', field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='financialtransaction', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='financialtransaction', name='created_by', field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL))
    ]
