# Generated by Django 5.2.17 on 2026-09-02 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finance_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accent_color',
            field=models.CharField(default='#8F172D', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a six-digit hex colour such as #8F172D.')]),
        ),
        migrations.AddField(
            model_name='business',
            name='restaurant_table_service',
            field=models.BooleanField(default=True, help_text='For restaurant businesses, capture a table/reference for dine-in sales.'),
        ),
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='vertical',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('restaurant', 'Restaurant / food service'), ('general', 'General production')], default='bakery', max_length=20),
        ),
    ]
