# Generated by Django 5.2.17 on 2026-08-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How many usage units in 1 purchase unit. E.g. 1 bag = 50 kg → 50. Same unit both ways → 1.', max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='purchase_unit',
            field=models.CharField(blank=True, default='', help_text='The unit you buy in — bag, carton, bowl…', max_length=20),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='usage_unit',
            field=models.CharField(blank=True, default='', help_text='The unit stock/recipes are tracked in — kg, sachet, litre…', max_length=20),
        ),
    ]
