# Generated by Django 5.2.17 on 2026-09-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finance_audit'),
        ('inventory', '0002_recipeitem_flexible_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalsupplydispense',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='operationalsupplydispense',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('fg_unpaid_issue', 'Unpaid product issue'), ('fg_wastage', 'Production wastage'), ('operational_dispense', 'Operational supply dispense'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
