# Generated by Django 5.2.17 on 2026-08-17 18:21

from django.db import migrations


def copy_unit_forward(apps, schema_editor):
    """Existing raw materials had one 'unit' used everywhere. Default both
    the purchase and usage unit to that same value with conversion_factor=1
    — this exactly preserves current behaviour for anything already entered.
    Edit each material afterwards (Inventory page) if its purchase unit
    actually differs from its usage unit (e.g. flour bought in bags, used
    in kg)."""
    RawMaterial = apps.get_model("inventory", "RawMaterial")
    for m in RawMaterial.objects.all():
        m.purchase_unit = m.unit
        m.usage_unit = m.unit
        m.conversion_factor = 1
        m.save(update_fields=["purchase_unit", "usage_unit", "conversion_factor"])


def copy_unit_backward(apps, schema_editor):
    RawMaterial = apps.get_model("inventory", "RawMaterial")
    for m in RawMaterial.objects.all():
        m.unit = m.usage_unit or m.purchase_unit
        m.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_finishedgood_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_unit_forward, copy_unit_backward),
    ]
