# Generated by Django 5.2.17 on 2026-08-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_copy_unit_to_purchase_and_usage_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit',
        ),
    ]
