# Generated by Django 5.2.17 on 2026-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_rawmaterial_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How many usage units in 1 purchase unit. E.g. 1 bag = 50 kg → 50. Same unit both ways → 1.', max_digits=12),
        ),
    ]
