# Generated by Django 5.2.17 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_rawmaterial_conversion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='package_qty',
            field=models.DecimalField(decimal_places=2, default=1, help_text='How much is inside ONE purchase unit. E.g. 1 bag = 50 → 50.', max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='package_unit',
            field=models.CharField(blank=True, default='', help_text="The unit package_qty is measured in — kg, g, litre… (what's printed on the pack)", max_length=20),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='usage_conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, help_text="How many usage units in ONE package_unit. Standard: kg→g is 1000, litre→ml is 1000, same unit both ways is 1. Non-standard (spoon, cap…): count it yourself, e.g. 'my spoon holds 5g' → if package_unit is kg, that's 200 spoons per kg → 200.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purchase_unit',
            field=models.CharField(blank=True, default='', help_text='What you buy — bag, carton, pack…', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='usage_unit',
            field=models.CharField(blank=True, default='', help_text='The fine unit recipes actually consume — kg, g, spoon, cap…', max_length=20),
        ),
    ]
