# Generated by Django 5.2.17 on 2026-08-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_copy_conversion_factor_to_package_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='conversion_factor',
        ),
    ]
