# Generated by Django 5.2.17 on 2026-08-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_old_conversion_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='qty_per_unit',
            new_name='qty_per_batch',
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='units_per_batch',
            field=models.DecimalField(decimal_places=2, default=1, help_text="How many individual units one production batch makes, e.g. 41 loaves per batch. Recipe quantities are per BATCH, not per unit. Leave at 1 if you don't produce in batches.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='finishedgood',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='In individual units, not batches.', max_digits=12),
        ),
    ]
