# Generated by Django 5.2.17 on 2026-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_qty_per_unit_recipeitem_qty_per_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='total_produced',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative all-time production (customer orders + physical store restocks). Never decreases — a running total, not current stock.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='finishedgood',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Physical store (shelf) stock — available to sell right now.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='qty_per_batch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
