# Generated by Django 5.2.17 on 2026-08-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_finishedgood_total_produced_alter_finishedgood_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='total_delivered_to_customers',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative units delivered via completed customer orders. Only updates when an order is completed — same timing as physical store stock, not when merely ordered.', max_digits=14),
        ),
    ]
