# Generated by Django 5.2.17 on 2026-08-22 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0011_finishedgood_total_delivered_to_customers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('adjustment', 'Adjustment')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Signed quantity in the item's internal stock unit.", max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock balance immediately after this movement.', max_digits=14)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finished_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.finishedgood')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
