# Generated by Django 5.2.17 on 2026-08-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='affects_stock',
            field=models.BooleanField(default=True, help_text="Whether this movement changes the item's physical stock balance."),
        ),
    ]
