# Generated by Django 5.2.17 on 2026-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rawmaterial_category_productionmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.CharField(choices=[('ingredient', 'Ingredient'), ('packaging', 'Packaging'), ('production_supply', 'Production supply (Gas)'), ('operational_supply', 'Operational supply (Gloves, Cleaning, etc.)')], default='ingredient', help_text='Classifies how the material is used. Operational supplies are not tied to a production recipe.', max_length=24),
        ),
    ]
