# Generated by Django 5.2.17 on 2026-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_historical_costing_and_channel_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgood',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='For Physical Store ONLY.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='finishedgood',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional - Physical Store (shelf) Stock.', max_digits=12, null=True),
        ),
    ]
