import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("accounts","0007_subscription_plans_and_commerce_module"),
        ("core","0005_add_wholesale_retail_verticals"),
        ("inventory","0007_widen_usage_conversion_precision"),
        ("production","0019_productionbatch_excess_market_stock_units"),
        ("sales","0006_sale_service_mode_sale_table_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(name="CommerceSettings", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),
            ("enabled",models.BooleanField(default=False)),("hosted_storefront_enabled",models.BooleanField(default=True)),("order_now_link_enabled",models.BooleanField(default=True)),("api_enabled",models.BooleanField(default=True)),
            ("insufficient_stock_policy",models.CharField(choices=[("reduce","Reduce to available stock"),("reject","Reject when stock is insufficient"),("invite_preorder","Invite customer to switch to Pre-order"),("split","Split: fulfil available stock and pre-order the balance")],default="invite_preorder",max_length=20)),("public_note",models.CharField(blank=True,default="",max_length=255)),
            ("business",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="commerce_commercesettings_set",to="core.business")),("created_by",models.ForeignKey(blank=True,help_text="Who made this entry. Null for records created before this field existed.",null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commerce_commercesettings_created",to=settings.AUTH_USER_MODEL)),
        ], options={"verbose_name_plural":"commerce settings","constraints":[models.UniqueConstraint(fields=("business",),name="one_commerce_settings_per_business")]}),
        migrations.CreateModel(name="CommerceIntegration", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=100)),("integration_type",models.CharField(choices=[("api","Headless API"),("webhook","Platform webhook / connector")],default="api",max_length=12)),("api_key",models.CharField(editable=False,max_length=80,unique=True)),("webhook_secret",models.CharField(blank=True,default="",max_length=80)),("active",models.BooleanField(default=True)),("allowed_origin",models.CharField(blank=True,default="",max_length=255)),
            ("business",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="commerce_commerceintegration_set",to="core.business")),("created_by",models.ForeignKey(blank=True,help_text="Who made this entry. Null for records created before this field existed.",null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commerce_commerceintegration_created",to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name="StorefrontProduct", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("published",models.BooleanField(default=False)),("public_name",models.CharField(blank=True,default="",max_length=140)),("description",models.TextField(blank=True,default="")),("image_url",models.URLField(blank=True,default="")),("allow_stock_order",models.BooleanField(default=True)),("allow_preorder",models.BooleanField(default=True)),("min_quantity",models.DecimalField(decimal_places=2,default=1,max_digits=14)),("max_quantity",models.DecimalField(blank=True,decimal_places=2,max_digits=14,null=True)),("preorder_min_quantity",models.DecimalField(decimal_places=2,default=1,max_digits=14)),("preorder_lead_time",models.CharField(blank=True,default="",max_length=80)),
            ("business",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="commerce_storefrontproduct_set",to="core.business")),("created_by",models.ForeignKey(blank=True,help_text="Who made this entry. Null for records created before this field existed.",null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commerce_storefrontproduct_created",to=settings.AUTH_USER_MODEL)),("finished_good",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="storefront_product",to="inventory.finishedgood")),
        ], options={"ordering":["finished_good__name"]}),
        migrations.CreateModel(name="CommerceIntake", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("public_number",models.CharField(blank=True,default="",max_length=40)),("source",models.CharField(choices=[("storefront","Hosted storefront"),("api","API"),("connector","External connector")],default="storefront",max_length=12)),("external_order_id",models.CharField(blank=True,default="",max_length=120)),("idempotency_key",models.CharField(blank=True,default="",max_length=120)),("ordering_mode",models.CharField(choices=[("stock","Order"),("preorder","Pre-order")],max_length=12)),("status",models.CharField(choices=[("pending","Pending review"),("accepted","Accepted"),("awaiting_preorder","Awaiting Pre-order confirmation"),("rejected","Rejected"),("cancelled","Cancelled"),("fulfilled","Fulfilled")],default="pending",max_length=20)),("customer_name",models.CharField(max_length=160)),("customer_phone",models.CharField(blank=True,default="",max_length=40)),("customer_email",models.EmailField(blank=True,default="",max_length=254)),("customer_address",models.TextField(blank=True,default="")),("service_mode",models.CharField(blank=True,default="",max_length=20)),("table_reference",models.CharField(blank=True,default="",max_length=40)),("payment_state",models.CharField(choices=[("pending","Pending"),("confirmed","Confirmed"),("failed","Failed")],default="pending",max_length=12)),("fulfilment_state",models.CharField(choices=[("pending","Pending"),("partial","Partial"),("complete","Complete")],default="pending",max_length=12)),("rejection_reason",models.CharField(blank=True,default="",max_length=255)),
            ("accepted_order",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commerce_intakes",to="production.order")),("accepted_sale",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commerce_intakes",to="sales.sale")),("split_order",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="split_commerce_intakes",to="production.order")),("business",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="commerce_commerceintake_set",to="core.business")),("created_by",models.ForeignKey(blank=True,help_text="Who made this entry. Null for records created before this field existed.",null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="commerce_commerceintake_created",to=settings.AUTH_USER_MODEL)),
        ], options={"ordering":["-created_at","-id"],"constraints":[models.UniqueConstraint(condition=~models.Q(external_order_id=""),fields=("business","source","external_order_id"),name="unique_external_commerce_order"),models.UniqueConstraint(condition=~models.Q(idempotency_key=""),fields=("business","source","idempotency_key"),name="unique_commerce_idempotency_key")]}),
        migrations.CreateModel(name="CommerceIntakeItem", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("requested_quantity",models.DecimalField(decimal_places=2,max_digits=14)),("accepted_stock_quantity",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("production_quantity",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("unit_price",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("finished_good",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="inventory.finishedgood")),("intake",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="items",to="commerce.commerceintake")),("storefront_product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="commerce.storefrontproduct")),
        ]),
    ]
