# Generated by Django 5.2.17 on 2026-09-06 23:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_commerce_connector_toggle'),
        ('core', '0005_add_wholesale_retail_verticals'),
        ('sales', '0006_sale_service_mode_sale_table_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceintake',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='commerceintake',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commerceintegration',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='commerceintegration',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commercesettings',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='commercesettings',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storefrontproduct',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='storefrontproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommercePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method', models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify'), ('bank_transfer', 'Bank transfer'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_customer', 'Awaiting customer'), ('awaiting_verification', 'Awaiting verification'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('gateway_reference', models.CharField(blank=True, default='', max_length=160)),
                ('authorization_url', models.URLField(blank=True, default='', max_length=500)),
                ('instructions', models.CharField(blank=True, default='', max_length=500)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('return_url', models.URLField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('gateway_metadata', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.commerceintake')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_commerce_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommerceGatewayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify')], max_length=20)),
                ('event_key', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('signature_valid', models.BooleanField(default=False)),
                ('provider_verified', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_events', to='commerce.commercepayment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommercePaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_name', models.CharField(max_length=160)),
                ('transfer_reference', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('submitted', 'Awaiting verification'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('mismatch_reason', models.CharField(blank=True, default='', max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='commerce.commercepayment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_commerce_payment_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommercePaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('paystack_enabled', models.BooleanField(default=False)),
                ('paystack_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('monnify_enabled', models.BooleanField(default=False)),
                ('monnify_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('monnify_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('monnify_contract_code', models.CharField(blank=True, default='', max_length=80)),
                ('monnify_base_url', models.URLField(default='https://api.monnify.com')),
                ('bank_transfer_enabled', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=160)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=40)),
                ('bank_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('cash_enabled', models.BooleanField(default=False)),
                ('cash_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('bank_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_bank_transfer_configurations', to='core.cashaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_cash_configurations', to='core.cashaccount')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('monnify_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_monnify_configurations', to='core.cashaccount')),
                ('paystack_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_paystack_configurations', to='core.cashaccount')),
            ],
            options={
                'verbose_name': 'commerce payment configuration',
            },
        ),
        migrations.CreateModel(
            name='CommercePaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('external_reference', models.CharField(blank=True, default='', max_length=160)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('verified_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_receipts', to='core.cashaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('financial_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_receipt', to='core.financialtransaction')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='commerce.commercepayment')),
                ('reversal_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_receipt_reversal', to='core.financialtransaction')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_commerce_payment_receipts', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommercePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('customer_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_allocation', to='sales.customerpayment')),
                ('reversal_customer_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_reversal_allocation', to='sales.customerpayment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment_allocations', to='sales.sale')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='commerce.commercepaymentreceipt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commercepayment',
            constraint=models.UniqueConstraint(fields=('business', 'intake', 'idempotency_key'), name='unique_commerce_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='commercegatewayevent',
            constraint=models.UniqueConstraint(fields=('business', 'provider', 'event_key'), name='unique_commerce_gateway_event'),
        ),
        migrations.AddConstraint(
            model_name='commercepaymentclaim',
            constraint=models.UniqueConstraint(fields=('business', 'transfer_reference'), name='unique_commerce_transfer_reference'),
        ),
        migrations.AddConstraint(
            model_name='commercepaymentconfiguration',
            constraint=models.UniqueConstraint(fields=('business',), name='one_commerce_payment_config_per_business'),
        ),
        migrations.AddConstraint(
            model_name='commercepaymentreceipt',
            constraint=models.UniqueConstraint(fields=('business', 'payment', 'idempotency_key'), name='unique_commerce_receipt_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='commercepaymentreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('business', 'external_reference'), name='unique_settled_commerce_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='commercepaymentallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'sale'), name='unique_commerce_receipt_sale_allocation'),
        ),
    ]
