# Generated by Django 5.2.17 on 2026-09-07 00:21

from django.db import migrations, models
from django.db.models import F


def preserve_existing_channel_intent(apps, schema_editor):
    CommerceIntake = apps.get_model("commerce", "CommerceIntake")
    CommerceIntake.objects.filter(ordering_mode="preorder").update(sales_channel="online")


def preserve_existing_product_publication(apps, schema_editor):
    StorefrontProduct = apps.get_model("commerce", "StorefrontProduct")
    production_verticals = ("bakery", "restaurant", "general")
    StorefrontProduct.objects.update(allow_distribution_order=False, allow_online_order=False)
    StorefrontProduct.objects.filter(business__vertical__in=production_verticals).update(
        allow_online_order=F("allow_preorder")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_commerceintake_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerceintake',
            name='sales_channel',
            field=models.CharField(choices=[('physical_store', 'Physical Store'), ('online', 'Online'), ('distribution', 'Distribution / Bulk')], default='physical_store', max_length=20),
        ),
        migrations.RunPython(preserve_existing_channel_intent, migrations.RunPython.noop),
        migrations.AddField(
            model_name='storefrontproduct',
            name='allow_distribution_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storefrontproduct',
            name='allow_online_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storefrontproduct',
            name='distribution_min_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
        migrations.RunPython(preserve_existing_product_publication, migrations.RunPython.noop),
    ]
