# Generated by Django 5.2.17 on 2026-09-07 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_commerce_order_sequences(apps, schema_editor):
    CommerceIntake = apps.get_model("commerce", "CommerceIntake")
    CommerceOrderNumberSequence = apps.get_model("commerce", "CommerceOrderNumberSequence")
    highest_by_business = {}
    for business_id, public_number in CommerceIntake.objects.exclude(public_number="").values_list(
        "business_id", "public_number"
    ):
        prefix, separator, suffix = public_number.rpartition("-")
        if separator and prefix == "WEB" and suffix.isdigit():
            highest_by_business[business_id] = max(
                highest_by_business.get(business_id, 0), int(suffix)
            )
    for business_id, highest in highest_by_business.items():
        CommerceOrderNumberSequence.objects.update_or_create(
            business_id=business_id,
            defaults={"next_number": highest + 1},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_commerceintake_sales_channel_and_more'),
        ('core', '0005_add_wholesale_retail_verticals'),
        ('production', '0019_productionbatch_excess_market_stock_units'),
        ('sales', '0006_sale_service_mode_sale_table_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceOrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.AddConstraint(
            model_name='commerceintake',
            constraint=models.UniqueConstraint(condition=models.Q(('public_number', ''), _negated=True), fields=('business', 'public_number'), name='unique_commerce_number_per_business'),
        ),
        migrations.AddField(
            model_name='commerceordernumbersequence',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='commerceordernumbersequence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who made this entry. Null for records created before this field existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='commerceordernumbersequence',
            constraint=models.UniqueConstraint(fields=('business',), name='unique_commerce_order_sequence_per_business'),
        ),
        migrations.RunPython(seed_commerce_order_sequences, migrations.RunPython.noop),
    ]
