# Generated by Django 5.2.17 on 2026-09-07

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_commerceordernumbersequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontproduct",
            name="image",
            field=models.ImageField(blank=True, upload_to=commerce.models.storefront_product_image_upload_to),
        ),
    ]
