"""Presentation and workflow vocabulary for supported business verticals.

Stored model keys remain stable across verticals. Only labels and small
workflow preferences vary, which keeps reports and existing data compatible.
"""

from .models import Business


VERTICAL_CONFIG = {
    Business.VERTICAL_BAKERY: {
        "uses_production": True,
        "procures_finished_goods": False,
        "direct_sale_channel": "physical_store",
        "inventory_primary": "raw",
        "product_label": "Finished Goods",
        "recipe_label": "Recipe",
        "recipe_item_label": "Ingredient",
        "production_inputs_label": "Packaging & Kitchen Inputs",
        "process_label": "Bake / Prepare",
        "platform_label": "Bakery operations",
        "orders": "Orders",
        "runs": "Shared Runs",
        "batches": "Production Batches",
        "customers": "Customers",
        "sales": "Sales",
        "stock_location": "Physical Store",
        "sale_intro": "Physical Store Stock only — immediate, from what's already on the Shelf.",
        "order_types": [
            ("distribution", "Distribution Order"),
            ("online", "Online Order"),
            ("physical_store", "Physical Store Order"),
        ],
    },
    Business.VERTICAL_RESTAURANT: {
        "uses_production": True,
        "procures_finished_goods": False,
        "direct_sale_channel": "physical_store",
        "inventory_primary": "raw",
        "product_label": "Menu Items",
        "recipe_label": "Recipe",
        "recipe_item_label": "Ingredient",
        "production_inputs_label": "Packaging & Kitchen Inputs",
        "process_label": "Prepare / Cook",
        "platform_label": "Restaurant operations",
        "orders": "Kitchen Orders",
        "runs": "Prep Runs",
        "batches": "Prep Batches",
        "customers": "Guests & Customers",
        "sales": "POS Sales",
        "stock_location": "Kitchen / Counter",
        "sale_intro": "Record dine-in, takeaway, or delivery service from available prepared stock.",
        "order_types": [
            ("distribution", "Catering / Bulk Order"),
            ("online", "Delivery / Online Order"),
            ("physical_store", "Kitchen / Counter Replenishment"),
        ],
    },
    Business.VERTICAL_GENERAL: {
        "uses_production": True,
        "procures_finished_goods": False,
        "direct_sale_channel": "physical_store",
        "inventory_primary": "raw",
        "product_label": "Finished Goods",
        "recipe_label": "Formula / BOM",
        "recipe_item_label": "Component",
        "production_inputs_label": "Production Inputs",
        "process_label": "Manufacture / Assemble",
        "platform_label": "Production operations",
        "orders": "Production Orders",
        "runs": "Production Runs",
        "batches": "Production Batches",
        "customers": "Customers",
        "sales": "Sales",
        "stock_location": "Finished Goods Store",
        "sale_intro": "Record an immediate sale from available finished-goods stock.",
        "order_types": [
            ("distribution", "Wholesale / Customer Order"),
            ("online", "Online Order"),
            ("physical_store", "Stock Replenishment Order"),
        ],
    },
    Business.VERTICAL_WHOLESALE: {
        "uses_production": False,
        "procures_finished_goods": True,
        "direct_sale_channel": "distribution",
        "inventory_primary": "finished",
        "product_label": "Stock Products",
        "recipe_label": "Product Specification",
        "recipe_item_label": "Purchased Product",
        "production_inputs_label": "Supplier Inputs",
        "process_label": "Receive / Put Away",
        "platform_label": "Wholesale operations",
        "orders": "Stock Orders",
        "runs": "Stock Runs",
        "batches": "Stock Batches",
        "customers": "Trade Customers",
        "sales": "Wholesale Sales",
        "stock_location": "Warehouse Stock",
        "sale_intro": "Release available warehouse stock to a trade customer, with agreed pricing and credit terms when applicable.",
        "order_types": [
            ("distribution", "Wholesale Order"),
            ("online", "Online Trade Order"),
            ("physical_store", "Warehouse Replenishment"),
        ],
    },
    Business.VERTICAL_RETAIL: {
        "uses_production": False,
        "procures_finished_goods": True,
        "direct_sale_channel": "physical_store",
        "inventory_primary": "finished",
        "product_label": "Stock Products",
        "recipe_label": "Product Specification",
        "recipe_item_label": "Purchased Product",
        "production_inputs_label": "Supplier Inputs",
        "process_label": "Receive / Shelve",
        "platform_label": "Retail operations",
        "orders": "Stock Orders",
        "runs": "Stock Runs",
        "batches": "Stock Batches",
        "customers": "Customers",
        "sales": "Retail Sales",
        "stock_location": "Shop Stock",
        "sale_intro": "Record an immediate retail sale from stock currently available in the shop.",
        "order_types": [
            ("distribution", "Bulk Customer Order"),
            ("online", "Online Order"),
            ("physical_store", "Shop Replenishment"),
        ],
    },
}


def vertical_config(business):
    key = getattr(business, "vertical", Business.VERTICAL_BAKERY)
    return VERTICAL_CONFIG.get(key, VERTICAL_CONFIG[Business.VERTICAL_GENERAL])
